name: oguz_kurye
description: "Uşak Kurye Kazanç ve Rota Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

flutter:
  uses-material-design: true
